from __future__ import annotations

import numpy as np
import pandas as pd

from features.v2_features import build_causal_v2_features


V12_NUMERIC_FEATURES = [
    "direction_num", "alignment_count", "h1_bias_num", "m15_bias_num", "m5_bias_num",
    "rsi14", "rsi_distance_50", "atr_pct", "atr_pctile_rolling", "atr_change_4h",
    "sweep_atr", "sweep_pct_range", "body_pct_range", "wick_pct_range",
    "upper_wick_pct", "lower_wick_pct", "wick_imbalance",
    "ema20_50_atr", "ema50_200_atr", "ema20_slope_4h_atr",
    "macd_atr", "macd_signal_atr", "macd_hist_atr",
    "return_1h", "return_4h", "return_8h",
    "risk_atr", "directional_rsi", "directional_macd_hist",
    "directional_return_4h", "directional_return_8h",
    "range_position_4h", "range_position_8h", "range_position_24h",
    "distance_recent_high_4h_atr", "distance_recent_low_4h_atr",
    "distance_recent_high_8h_atr", "distance_recent_low_8h_atr",
    "distance_recent_high_24h_atr", "distance_recent_low_24h_atr",
    "distance_prev_day_high_atr", "distance_prev_day_low_atr",
    "prev_day_sweep_up", "prev_day_sweep_down", "directional_prev_day_sweep",
    "ny_hour_sin", "ny_hour_cos", "dow_sin", "dow_cos",
]

V12_CATEGORICAL_FEATURES = ["killzone_name"]
V12_TARGETS = {"1R": "hit_1_0r", "1.5R": "hit_1_5r"}


def _col(df: pd.DataFrame, name: str) -> pd.Series:
    if name in df.columns:
        return pd.to_numeric(df[name], errors="coerce")
    return pd.Series(np.nan, index=df.index, dtype=float)


def build_causal_v1_2_features(dataset: pd.DataFrame, volatility_window: int = 200) -> pd.DataFrame:
    """Expanded leakage-safe features for CRT ML V1.2.

    Requires the research dataset generated by the updated run_research.py to
    fully populate market-structure and momentum fields. Missing legacy fields
    are left as NaN so the pipeline can fail softly during migration.
    """
    df = build_causal_v2_features(dataset, volatility_window=volatility_window)
    atr = _col(df, "atr14").replace(0, np.nan)
    direction = _col(df, "direction_num").fillna(0)

    df["rsi_distance_50"] = _col(df, "rsi14") - 50.0
    df["directional_rsi"] = direction * df["rsi_distance_50"]

    df["wick_imbalance"] = _col(df, "lower_wick_pct") - _col(df, "upper_wick_pct")
    df["ema20_slope_4h_atr"] = _col(df, "ema20_slope_4h") / atr
    df["macd_atr"] = _col(df, "macd") / atr
    df["macd_signal_atr"] = _col(df, "macd_signal") / atr
    df["macd_hist_atr"] = _col(df, "macd_hist") / atr
    df["directional_macd_hist"] = direction * df["macd_hist_atr"]
    df["directional_return_4h"] = direction * _col(df, "return_4h")
    df["directional_return_8h"] = direction * _col(df, "return_8h")

    prev_high = _col(df, "prev_day_high")
    prev_low = _col(df, "prev_day_low")
    high = _col(df, "high")
    low = _col(df, "low")
    df["prev_day_sweep_up"] = (high > prev_high).astype(float).where(prev_high.notna())
    df["prev_day_sweep_down"] = (low < prev_low).astype(float).where(prev_low.notna())
    df["directional_prev_day_sweep"] = np.where(
        direction > 0,
        df["prev_day_sweep_down"],
        np.where(direction < 0, df["prev_day_sweep_up"], np.nan),
    )
    return df
